import { describe,expect,it } from "vitest";import { service } from "../helpers.js";
describe("acceptance fixtures",()=>{
 it("short-video co-creation forms a framework, not transcript notices",async()=>{const {store,service:s}=service();const x=s.start({title:"短视频"});await s.capture({session_id:x.session_id,user_message:"写脚本并优化钩子",assistant_message:"完成首稿，钩子承诺明确收益"});await s.capture({session_id:x.session_id,user_message:"加入个人 IP 与情绪曲线",assistant_message:"完成脚本结构调整"});const md=s.export(x.session_id,"markdown").content;expect(md).toContain("知识框架");expect(md).not.toContain("已记录");store.close();});
 it("pause resume and only-new use real cursors",async()=>{const {store,service:s}=service();const x=s.start();await s.capture({session_id:x.session_id,user_message:"钩子",assistant_message:"完播率"});s.changeStatus({session_id:x.session_id,status:"paused"});const paused=await s.capture({session_id:x.session_id,user_message:"Excel",assistant_message:"数据透视"});expect(paused.operations).toHaveLength(0);const resume=s.changeStatus({session_id:x.session_id,status:"active",capture_scope:{mode:"topic",topic:"面试"}});expect(resume.resume_from_cursor).toBe(2);await s.capture({session_id:x.session_id,user_message:"面试方案",assistant_message:"结构化面试"});expect(store.listCards(x.session_id,{sinceCursor:2})).toHaveLength(1);store.close();});
 it("handles an unseeded domain fixture",async()=>{const {store,service:s}=service();const x=s.start();await s.capture({session_id:x.session_id,user_message:"如何做 Excel 销售分析",assistant_message:"先定义指标粒度，再用数据透视表"});expect(store.listCards(x.session_id)[0]?.title).toContain("Excel");store.close();});
 it("is idempotent for repeated turn submissions",async()=>{const {store,service:s}=service();const x=s.start();const input={session_id:x.session_id,user_message:"钩子",assistant_message:"提升完播率",source_reference:"host-turn-1"};const a=await s.capture(input);const b=await s.capture(input);expect(a.idempotent_replay).toBe(false);expect(b.idempotent_replay).toBe(true);expect(store.listTurns(x.session_id)).toHaveLength(1);store.close();});
 it("uses a safe fallback title and supports renaming",()=>{const {store,service:s}=service();const x=s.start({title:"  "});expect(x.title).toBe("待命名学习会话");expect(s.renameSession({session_id:x.session_id,title:"  GPT 生成的学习主题  "}).title).toBe("GPT 生成的学习主题");expect(()=>s.renameSession({session_id:x.session_id,title:"  "})).toThrow(/title is required/);store.close();});
 it("reconstructs exports from complete turns",async()=>{const {store,service:s}=service();const x=s.start();await s.capture({session_id:x.session_id,user_message:"怀疑网络故障",assistant_message:"假设"});await s.capture({session_id:x.session_id,user_message:"连接通过，证书时间失败",assistant_message:"TLS 时钟结论"});const md=s.export(x.session_id,"markdown").content;expect(md).toContain("按知识依赖重构");expect(md.indexOf("TLS 失败")).toBeGreaterThan(-1);expect(md).not.toContain("故障假设：网络不可达");expect(s.export(x.session_id,"mermaid").content).toMatch(/^mindmap/);expect(JSON.parse(s.export(x.session_id,"json").content).turns).toHaveLength(2);store.close();});
});
