import { App } from "@modelcontextprotocol/ext-apps";
import "./style.css";
type Card=any; type State={session:any;cursor:number;cards:Card[];learning_debts:Card[];recent_cards?:Card[]};
const root=document.querySelector<HTMLDivElement>("#app")!;let state:State|null=null;let sessionId=new URLSearchParams(location.search).get("session")??localStorage.getItem("kc-session")??"";let since=Number(localStorage.getItem(`kc-seen-${sessionId}`)??0);let filter="all";let embedded=false;let mcp:App|null=null;
const eventLabel=(c:Card)=>c.lifecycle==="superseded"?"已替换":c.lifecycle==="discarded"?"已废弃":c.revision>1?"已修订":c.revision===1?"新增":"";
function cardView(c:Card){return `<details class="card ${c.lifecycle} revision-${c.revision}"><summary><span class="kind">${c.type}</span><b>${esc(c.title)}</b><span class="event">${eventLabel(c)}</span></summary><p>${esc(c.summary)}</p>${c.operation?`<dl><dt>实际作用</dt><dd>${esc(c.operation.actual_effect)}</dd><dt>目的</dt><dd>${esc(c.operation.current_purpose)}</dd><dt>机制</dt><dd>${esc(c.operation.mechanism)}</dd><dt>验证</dt><dd>${esc(c.operation.verification.join("；"))}</dd><dt>风险</dt><dd>${esc(c.operation.risks.join("；"))}</dd><dt>可逆性</dt><dd>${c.operation.reversibility}</dd></dl>`:""}${c.learning_debt?`<p class="debt">${esc(c.learning_debt.question)} · ${c.learning_debt.recommended_stage}</p>`:""}<div class="sources">来源：${c.provenance.map((p:any)=>esc(p.turn_ref)).join("、")}</div><button data-status="mastered" data-id="${c.card_id}">已掌握</button><button data-status="review" data-id="${c.card_id}">待复习</button></details>`}
function esc(x:string){const d=document.createElement("div");d.textContent=x??"";return d.innerHTML;}
function render(){if(!state){root.innerHTML=`<main><h1>对话知识副驾驶</h1><p>创建或输入会话 ID。面板只显示显式捕获并持久化的数据。</p><form id="start"><input id="title" placeholder="会话标题"><button>创建会话</button></form><form id="open"><input id="sid" placeholder="session_id"><button>打开</button></form></main>`;bind();return;}
 const all=state.cards.filter(c=>filter==="all"||c.type===filter);const fresh=(state.recent_cards??[]).filter(c=>(filter==="all"||c.type===filter)&&c.lifecycle==="active");
 root.innerHTML=`<main><header><div><p class="eyebrow">REAL CURSOR ${state.cursor}</p><h1>${esc(state.session.title)}</h1><p>${state.session.status} · ${esc(state.session.capture_scope.topic??"全部主题")}</p></div><div><button id="toggle">${state.session.status==="active"?"暂停":"恢复"}</button><button id="refresh">刷新</button></div></header><nav>${["all","concept","principle","method","operation","framework","correction","learning_debt"].map(t=>`<button data-filter="${t}" class="${filter===t?"active":""}">${t}</button>`).join("")}</nav><section><h2>本轮新增 <span>${fresh.length}</span></h2><div class="grid">${fresh.map(cardView).join("")||"<p class=empty>真实游标之后暂无新增。</p>"}</div><button id="mark-seen">只看新增边界标记为 ${state.cursor}</button></section><section><h2>全部知识</h2><div class="grid">${all.map(cardView).join("")||"<p class=empty>暂无卡片。请由宿主或调试接口提交完整轮次。</p>"}</div></section><section><h2>待深挖</h2>${state.learning_debts.map(cardView).join("")||"<p class=empty>暂无学习债务。</p>"}</section><section><h2>笔记与思维导图</h2><div class="exports"><button data-export="markdown">Markdown 笔记</button><button data-export="mermaid">Mermaid 思维导图</button><button data-export="json">JSON 完整导出</button></div><pre id="export"></pre></section><details><summary>开发调试：提交一轮</summary><form id="capture"><textarea id="user" placeholder="用户消息"></textarea><textarea id="assistant" placeholder="助手消息"></textarea><button>捕获完成轮次</button></form></details></main>`;bind();}
async function call(name:string,args:any){if(embedded&&mcp){const r=await mcp.callServerTool({name,arguments:args});const text=(r.content as any[])?.find(x=>x.type==="text")?.text;return text?JSON.parse(text):r.structuredContent;}const routes:any={start_learning_session:["/api/sessions","POST"],capture_conversation_turn:[`/api/sessions/${args.session_id}/capture`,"POST"],get_learning_session:[`/api/sessions/${args.session_id}`,"GET"],list_knowledge_cards:[`/api/sessions/${args.session_id}/cards?since_cursor=${args.since_cursor??0}&include_inactive=${args.include_inactive??false}`,"GET"],change_capture_status:[`/api/sessions/${args.session_id}/status`,"POST"],change_card_learning_status:[`/api/cards/${args.card_id}/status`,"POST"],export_learning_package:[`/api/sessions/${args.session_id}/export/${args.format}`,"GET"]};const [url,method]=routes[name];const copy={...args};delete copy.session_id;delete copy.card_id;delete copy.format;const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:method==="GET"?undefined:JSON.stringify(copy)});if(!r.ok)throw new Error((await r.json()).error);return r.json();}
async function load(){if(!sessionId){state=null;render();return;}state=await call("get_learning_session",{session_id:sessionId});const recent=await call("list_knowledge_cards",{session_id:sessionId,since_cursor:since,include_inactive:true});state!.recent_cards=recent.cards;localStorage.setItem("kc-session",sessionId);render();}
function bind(){document.querySelector<HTMLFormElement>("#start")?.addEventListener("submit",async e=>{e.preventDefault();const s=await call("start_learning_session",{title:(document.querySelector<HTMLInputElement>("#title")!).value,source_host:embedded?"mcp-app":"preview"});sessionId=s.session_id;await load();});document.querySelector<HTMLFormElement>("#open")?.addEventListener("submit",async e=>{e.preventDefault();sessionId=(document.querySelector<HTMLInputElement>("#sid")!).value;await load();});document.querySelector("#refresh")?.addEventListener("click",load);document.querySelector("#toggle")?.addEventListener("click",async()=>{await call("change_capture_status",{session_id:sessionId,status:state!.session.status==="active"?"paused":"active"});await load();});document.querySelector("#mark-seen")?.addEventListener("click",()=>{since=state!.cursor;localStorage.setItem(`kc-seen-${sessionId}`,String(since));render();});document.querySelectorAll<HTMLElement>("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter!;render();});document.querySelectorAll<HTMLElement>("[data-status]").forEach(b=>b.onclick=async()=>{await call("change_card_learning_status",{card_id:b.dataset.id,status:b.dataset.status});await load();});document.querySelectorAll<HTMLElement>("[data-export]").forEach(b=>b.onclick=async()=>{const x=await call("export_learning_package",{session_id:sessionId,format:b.dataset.export});document.querySelector("#export")!.textContent=x.content;});document.querySelector<HTMLFormElement>("#capture")?.addEventListener("submit",async e=>{e.preventDefault();await call("capture_conversation_turn",{session_id:sessionId,user_message:(document.querySelector<HTMLTextAreaElement>("#user")!).value,assistant_message:(document.querySelector<HTMLTextAreaElement>("#assistant")!).value,source_reference:`preview-${Date.now()}`});await load();});}
embedded=window.parent!==window;if(embedded){try{mcp=new App({name:"Knowledge Copilot Panel",version:"0.1.0"});mcp.ontoolresult=r=>{const text=(r.content as any[])?.find(x=>x.type==="text")?.text;if(text){const parsed=JSON.parse(text);if(parsed.session){state=parsed;sessionId=parsed.session.session_id;render();}}};await mcp.connect();}catch{embedded=false;mcp=null;}}await load();
